# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceec39e86d05d052e81aebec00b42b4f5d863abe7a01aa62370bb67c39205aaad3a67d53d6c8d7b7ba3689e9d29a8e636bdbfb3e9cdd17ec0a174015097b04fd

test:
  secret_key_base: d6f6c54d378d1bc31e74dc44b26a0d45ee0254d038383379f5dafec0b2752313c0fd63dc35a94d2929bf726d3dd0803941ce7ea287a2536776cc20a8c7f126b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
