google:
  key: "<%= ENV['GOOGLE_CLIENT_KEY'] %>"
  secret: "<%= ENV['GOOGLE_CLIENT_SECRET'] %>"

smtp:
  user_name: "<%= ENV['SMTP_USER_NAME'] %>"
  password: "<%= ENV['SMTP_PASSWORD'] %>"
  domain: "<%= ENV['SMTP_DOMAIN'] %>"
  address: "<%= ENV['SMTP_ADDRESS'] %>"
  port: "<%= ENV['SMTP_PORT'] %>"
  host: "<%= ENV['SMTP_HOST'] %>"

delayed_jobs:
  enabled: <%= !!ENV['DELAYED_JOBS_ENABLED'] %>

mailer:
  test_recipient: "<%= ENV['EMAIL_TEST_RECIPIENT'] %>"
